"""create initial schema

Revision ID: b3ec154e86a0
Revises: 
Create Date: 2026-09-07 17:57:35.290145

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3ec154e86a0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='user_role', native_enum=False), server_default=sa.text("'member'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('daily_query_limit', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_query_limit BETWEEN 1 AND 10000', name=op.f('ck_users_daily_query_limit_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('benchmark_versions',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='benchmark_status', native_enum=False), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_commit', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_benchmark_versions_created_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_versions'))
    )
    op.create_index('uq_benchmark_versions_name_version', 'benchmark_versions', ['name', 'version'], unique=True)
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_user_id_updated_at', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('documents',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=160), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'queued', 'processing', 'indexed', 'failed', 'deleting', name='document_status', native_enum=False), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'shared', name='visibility', native_enum=False), server_default=sa.text("'private'"), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('chunker_version', sa.String(length=40), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_count IS NULL OR page_count BETWEEN 1 AND 300', name=op.f('ck_documents_page_count_range')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_documents_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_owner_id', 'documents', ['owner_id'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_visibility', 'documents', ['visibility'], unique=False)
    op.create_index('uq_documents_owner_id_sha256', 'documents', ['owner_id', 'sha256'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('uq_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(heading, '') || ' ' || content)", persisted=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_end >= page_start', name=op.f('ck_chunks_page_end_after_start')),
    sa.CheckConstraint('page_start >= 1', name=op.f('ck_chunks_page_start_min')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_search_vector', 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('uq_chunks_document_id_checksum', 'chunks', ['document_id', 'checksum'], unique=True)
    op.create_index('uq_chunks_document_id_ordinal', 'chunks', ['document_id', 'ordinal'], unique=True)
    op.create_table('eval_runs',
    sa.Column('benchmark_version_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='eval_status', native_enum=False), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('retrieval_mode', sa.Enum('lexical', 'dense', 'hybrid', 'reranked_hybrid', name='retrieval_mode', native_enum=False), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('candidate_k', sa.Integer(), nullable=False),
    sa.Column('rrf_k', sa.Integer(), nullable=False),
    sa.Column('reranker_model', sa.String(length=160), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=False),
    sa.Column('corpus_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('top_k BETWEEN 1 AND 100', name=op.f('ck_eval_runs_top_k_range')),
    sa.ForeignKeyConstraint(['benchmark_version_id'], ['benchmark_versions.id'], name=op.f('fk_eval_runs_benchmark_version_id_benchmark_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_eval_runs_created_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_runs'))
    )
    op.create_index('ix_eval_runs_benchmark_version_id_created_at', 'eval_runs', ['benchmark_version_id', 'created_at'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'succeeded', 'failed', 'cancelled', name='job_status', native_enum=False), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ingestion_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_index('ix_ingestion_jobs_status_created_at', 'ingestion_jobs', ['status', 'created_at'], unique=False)
    op.create_index('uq_ingestion_jobs_active_document', 'ingestion_jobs', ['document_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieval_mode', sa.Enum('lexical', 'dense', 'hybrid', 'reranked_hybrid', name='retrieval_mode', native_enum=False), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('answer_status', sa.Enum('answered', 'insufficient_evidence', 'generation_failed', name='answer_status', native_enum=False), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('feedback',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.Enum('helpful', 'retrieval_miss', 'ranking_error', 'chunking_error', 'unsupported_answer', 'citation_error', 'source_gap', 'user_expectation', 'other', name='feedback_reason', native_enum=False), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('unresolved', 'resolved', 'ignored', 'promoted_to_draft', name='feedback_status', native_enum=False), server_default=sa.text("'unresolved'"), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('comment IS NULL OR char_length(comment) <= 2000', name=op.f('ck_feedback_comment_max_length')),
    sa.CheckConstraint('rating IN (0, 1)', name=op.f('ck_feedback_rating_binary')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_feedback_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_feedback_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index('uq_feedback_user_id_message_id', 'feedback', ['user_id', 'message_id'], unique=True)
    op.create_table('retrieval_results',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('retrieval_mode', sa.Enum('lexical', 'dense', 'hybrid', 'reranked_hybrid', name='retrieval_mode', native_enum=False), nullable=False),
    sa.Column('lexical_rank', sa.Integer(), nullable=True),
    sa.Column('dense_rank', sa.Integer(), nullable=True),
    sa.Column('fused_rank', sa.Integer(), nullable=True),
    sa.Column('rerank_rank', sa.Integer(), nullable=True),
    sa.Column('lexical_score', sa.Double(), nullable=True),
    sa.Column('dense_score', sa.Double(), nullable=True),
    sa.Column('fused_score', sa.Double(), nullable=True),
    sa.Column('rerank_score', sa.Double(), nullable=True),
    sa.Column('selected_for_context', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_retrieval_results_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_retrieval_results_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_results'))
    )
    op.create_index('ix_retrieval_results_chunk_id', 'retrieval_results', ['chunk_id'], unique=False)
    op.create_index('ix_retrieval_results_message_id', 'retrieval_results', ['message_id'], unique=False)
    op.create_index('uq_retrieval_results_message_id_chunk_id', 'retrieval_results', ['message_id', 'chunk_id'], unique=True)
    op.create_table('benchmark_cases',
    sa.Column('benchmark_version_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty', native_enum=False), nullable=False),
    sa.Column('split', sa.Enum('train', 'validation', 'test', name='dataset_split', native_enum=False), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_feedback_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(question) BETWEEN 10 AND 1000', name=op.f('ck_benchmark_cases_question_length')),
    sa.ForeignKeyConstraint(['benchmark_version_id'], ['benchmark_versions.id'], name=op.f('fk_benchmark_cases_benchmark_version_id_benchmark_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_feedback_id'], ['feedback.id'], name=op.f('fk_benchmark_cases_source_feedback_id_feedback'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_cases'))
    )
    op.create_index('uq_benchmark_cases_benchmark_version_id_external_id', 'benchmark_cases', ['benchmark_version_id', 'external_id'], unique=True)
    op.create_table('feedback_corrections',
    sa.Column('feedback_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('relevance', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('relevance BETWEEN 1 AND 3', name=op.f('ck_feedback_corrections_relevance_range')),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_feedback_corrections_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('fk_feedback_corrections_feedback_id_feedback'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', 'chunk_id', name=op.f('pk_feedback_corrections'))
    )
    op.create_table('eval_results',
    sa.Column('eval_run_id', sa.Uuid(), nullable=False),
    sa.Column('benchmark_case_id', sa.Uuid(), nullable=False),
    sa.Column('ranked_chunk_ids', postgresql.ARRAY(sa.Uuid()), nullable=True),
    sa.Column('ranked_relevances', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('hit_at_5', sa.Double(), nullable=True),
    sa.Column('recall_at_5', sa.Double(), nullable=True),
    sa.Column('reciprocal_rank', sa.Double(), nullable=True),
    sa.Column('ndcg_at_10', sa.Double(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_case_id'], ['benchmark_cases.id'], name=op.f('fk_eval_results_benchmark_case_id_benchmark_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], name=op.f('fk_eval_results_eval_run_id_eval_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_results'))
    )
    op.create_index('ix_eval_results_benchmark_case_id', 'eval_results', ['benchmark_case_id'], unique=False)
    op.create_index('ix_eval_results_eval_run_id', 'eval_results', ['eval_run_id'], unique=False)
    op.create_index('uq_eval_results_eval_run_id_benchmark_case_id', 'eval_results', ['eval_run_id', 'benchmark_case_id'], unique=True)
    op.create_table('relevance_judgments',
    sa.Column('benchmark_case_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('relevance', sa.SmallInteger(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('judged_by', sa.Uuid(), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('relevance BETWEEN 0 AND 3', name=op.f('ck_relevance_judgments_relevance_range')),
    sa.ForeignKeyConstraint(['benchmark_case_id'], ['benchmark_cases.id'], name=op.f('fk_relevance_judgments_benchmark_case_id_benchmark_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_relevance_judgments_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judged_by'], ['users.id'], name=op.f('fk_relevance_judgments_judged_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('benchmark_case_id', 'chunk_id', name=op.f('pk_relevance_judgments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relevance_judgments')
    op.drop_index('uq_eval_results_eval_run_id_benchmark_case_id', table_name='eval_results')
    op.drop_index('ix_eval_results_eval_run_id', table_name='eval_results')
    op.drop_index('ix_eval_results_benchmark_case_id', table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_table('feedback_corrections')
    op.drop_index('uq_benchmark_cases_benchmark_version_id_external_id', table_name='benchmark_cases')
    op.drop_table('benchmark_cases')
    op.drop_index('uq_retrieval_results_message_id_chunk_id', table_name='retrieval_results')
    op.drop_index('ix_retrieval_results_message_id', table_name='retrieval_results')
    op.drop_index('ix_retrieval_results_chunk_id', table_name='retrieval_results')
    op.drop_table('retrieval_results')
    op.drop_index('uq_feedback_user_id_message_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_ingestion_jobs_active_document', table_name='ingestion_jobs', postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.drop_index('ix_ingestion_jobs_status_created_at', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_eval_runs_benchmark_version_id_created_at', table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index('uq_chunks_document_id_ordinal', table_name='chunks')
    op.drop_index('uq_chunks_document_id_checksum', table_name='chunks')
    op.drop_index('ix_chunks_search_vector', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_document_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('uq_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_documents_owner_id_sha256', table_name='documents')
    op.drop_index('ix_documents_visibility', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_owner_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_user_id_updated_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('uq_benchmark_versions_name_version', table_name='benchmark_versions')
    op.drop_table('benchmark_versions')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
