"""add feedback_events audit table

Revision ID: d86ea0a29250
Revises: ea77790fc01d
Create Date: 2026-09-09 09:28:50.282921

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd86ea0a29250'
down_revision: str | Sequence[str] | None = 'ea77790fc01d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_events',
    sa.Column('feedback_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_feedback_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('fk_feedback_events_feedback_id_feedback'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_events'))
    )
    op.create_index('ix_feedback_events_feedback_id_created_at', 'feedback_events', ['feedback_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_events_feedback_id_created_at', table_name='feedback_events')
    op.drop_table('feedback_events')
    # ### end Alembic commands ###
