"""add document_sources

Revision ID: ea77790fc01d
Revises: b3ec154e86a0
Create Date: 2026-09-07 18:29:37.781163

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ea77790fc01d'
down_revision: str | Sequence[str] | None = 'b3ec154e86a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sources',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_sources_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document_sources'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_sources')
    # ### end Alembic commands ###
